#!/usr/bin/env bun
/**
 * Stage 4: Generate `docs/routing.md` — a marketplace-wide routing index.
 *
 * Reads every skill template's frontmatter (`name`, `description`,
 * `triggers`, `paths`) plus its owning plugin (from `plugins/<name>/plugin.yaml`)
 * and emits a concise per-plugin routing table. The output is meant to live
 * alongside the docs and be linked from preamble tier 3+.
 *
 * Usage:
 *   bun run build:routing                    # Generate
 *   bun run build:routing -- --dry-run       # Freshness check
 */

import * as fs from "fs";
import * as path from "path";
import {
  ROOT,
  findTemplates,
  loadAndParseTemplate,
  loadPlugins,
  buildSkillToPlugins,
  flattenDescription,
} from "./lib/skill-parser";
import YAML from "yaml";

const DRY_RUN = process.argv.includes("--dry-run");

function readTriggers(rawFrontmatter: string): string[] {
  if (!rawFrontmatter) return [];
  try {
    const parsed = (YAML.parse(rawFrontmatter) as Record<string, unknown>) ?? {};
    const t = parsed.triggers;
    if (Array.isArray(t)) return t.filter((x): x is string => typeof x === "string");
  } catch {
    // ignore
  }
  return [];
}

interface SkillRow {
  name: string;
  description: string;
  triggers: string[];
  paths: string[];
}

interface RoutingBuild {
  aggregate: string;
  fragments: Map<string, string>;
}

function tableForPlugin(pluginName: string, description: string, skills: SkillRow[]): string {
  const lines: string[] = [];
  lines.push(`## ${pluginName}`);
  lines.push("");
  lines.push(`> ${description}`);
  lines.push("");
  lines.push("| Skill | What it does | Triggers | Paths |");
  lines.push("|-------|--------------|----------|-------|");
  for (const s of skills) {
    const triggers = s.triggers.length > 0 ? s.triggers.map((x) => `\`${x}\``).join(", ") : "—";
    const paths = s.paths.length > 0 ? s.paths.map((x) => `\`${x}\``).join(", ") : "—";
    const desc = s.description.replaceAll("|", "\\|");
    lines.push(`| **${s.name}** | ${desc} | ${triggers} | ${paths} |`);
  }
  lines.push("");
  return lines.join("\n");
}

function buildRouting(): RoutingBuild {
  const templates = findTemplates();
  const plugins = loadPlugins();
  const skillToPlugins = buildSkillToPlugins(plugins);

  // Group skills by owning plugin.
  const byPlugin = new Map<string, SkillRow[]>();
  const orphans: SkillRow[] = [];

  for (const t of templates) {
    const parsed = loadAndParseTemplate(t);
    const row: SkillRow = {
      name: parsed.name || t.skillName,
      description: flattenDescription(parsed.description),
      triggers: readTriggers(parsed.rawFrontmatter),
      paths: parsed.paths,
    };
    const owners = skillToPlugins.get(t.skillName);
    if (!owners || owners.length === 0) {
      orphans.push(row);
      continue;
    }
    for (const owner of owners) {
      const list = byPlugin.get(owner.pluginName) ?? [];
      list.push(row);
      byPlugin.set(owner.pluginName, list);
    }
  }
  for (const list of byPlugin.values()) list.sort((a, b) => a.name.localeCompare(b.name));

  const lines: string[] = [];
  const fragments = new Map<string, string>();
  lines.push("# Routing Index");
  lines.push("");
  lines.push("<!-- AUTO-GENERATED by `bun run build:routing` — do not edit directly -->");
  lines.push("");
  lines.push(
    "Each skill is listed under its owning plugin. The **Triggers** column is " +
      "natural-phrasing input for routing decisions (matched flexibly, not as exact " +
      "slash-command names). The **Paths** column is the file-glob attachment scope " +
      "Cursor uses for Auto Attached rules and Claude uses to surface the skill " +
      "when those files are open.",
  );
  lines.push("");

  for (const plugin of plugins) {
    const skills = byPlugin.get(plugin.name);
    if (!skills || skills.length === 0) continue;
    const table = tableForPlugin(plugin.name, plugin.description, skills);
    lines.push(table.trimEnd(), "");
    fragments.set(plugin.name, [
      `# ${plugin.name} Routing`,
      "",
      "<!-- AUTO-GENERATED by `bun run build:routing` - do not edit directly -->",
      "",
      table,
    ].join("\n").trimEnd() + "\n");
  }

  if (orphans.length > 0) {
    lines.push("## Unassigned");
    lines.push("");
    lines.push("Skills with no owning plugin (likely scaffolded but not yet registered).");
    lines.push("");
    for (const o of orphans) lines.push(`- **${o.name}** — ${o.description}`);
    lines.push("");
  }

  return { aggregate: lines.join("\n"), fragments };
}

const built = buildRouting();
const content = built.aggregate;
const outputPath = path.join(ROOT, "docs", "routing.md");

if (DRY_RUN) {
  const existing = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, "utf-8") : "";
  if (existing !== content) {
    console.log(`STALE: docs/routing.md`);
    console.error("\nGenerated routing index is stale. Run: bun run build:routing");
    process.exit(1);
  }
  console.log(`FRESH: docs/routing.md`);
} else {
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, content);
  for (const [pluginName, fragment] of built.fragments) {
    const fragmentPath = path.join(ROOT, "plugins", pluginName, "routing.md");
    fs.writeFileSync(fragmentPath, fragment);
    console.log(`GENERATED: ${path.relative(ROOT, fragmentPath)}`);
  }
  const lines = content.split("\n").length;
  const tokens = Math.round(content.length / 4);
  console.log(`GENERATED: docs/routing.md (${lines} lines, ~${tokens} tokens)`);
}

console.log("\n✓ Routing generation complete.");
